version: '3'

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file: .env.development
    ports:
      - 7878:7878
    volumes:
      - ${PWD}:/app
      - ${PWD}/docker/volumes/target:/app/target
    restart: always
    depends_on:
      - database

  database:
    image: postgres:13
    env_file: .env.development
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/docker/volumes/database:/var/lib/postgresql/data
    restart: always
